### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by burner1024** [F3mic/F3mic.github.io#3]
> A macro is a collection of functions.

Not really. 
`#define LVAR_Gave_Xp;     (0)` is also a macro.

This is the proper reference for macros: https://gcc.gnu.org/onlinedocs/cpp/Macros.html

**Comment by F3mic** [comment]
Hi burn,

thanks for pointing that out.
It's on my agenda.

Regards.

**Comment by F3mic** [comment]
Done.
