### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by burner1024** [F3mic/F3mic.github.io#4]
> every variable inside the global namespace needs to have a unique name otherwise the engine gets confused and throws errors.

Engine does not see names for variables. It refers to variables by numbers (maybe except for import/export ones, not sure how these work). You can perfectly have
```
#define GVAR_1 120
#define GVAR_2 120
```
And use either in your scripts, it will work. (Although in general there's no reason to do this).

**Comment by F3mic** [comment]
Hi burn,

thanks for pointing that out.
It's on my agenda.

Regards.

**Comment by F3mic** [comment]
Done.
